# fly.toml app configuration file generated for hft-bot on 2025-05-04T13:03:50Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'hft-bot'
primary_region = 'cdg'

[build]
  [build.args]
    GO_VERSION = '1.24.0'

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  # Секция для health check(s)
  # [[http_service.checks]]
  #   interval = "30s"            # Интервал проверки (каждые 15 секунд)
  #   timeout = "5s"              # Таймаут проверки (ошибка через 5 секунд)
  #   grace_period = "10s"        # Период ожидания после старта машины (10 секунд)
  #   method = "GET"              # Метод HTTP запроса
  #   path = "/health"            # Путь к эндпоинту в вашем Go приложении
  #   protocol = "http"           # Протокол проверки (HTTP к internal_port)
  #   # port = 8080               # Порт (необязательно, если совпадает с internal_port)
  #   # [http_service.checks.headers] # Опциональные заголовки
  #   #   X-Health-Check = "true"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
